### ISSUE TITLE
White background

### ISSUE THREAD

**Issue by ramsestom** [restorer/zame-haxe-particles#7]
I am trying to get a "fire" particle animation working on a white background. It works well on a black background but is completely invisible on a white one. Why is that (particles are red or orange on the black background so they should appear on a white one too...)?
I don't really understand what parameter I am supposed tweak to make it appear on a white background..

EDIT: OK I achieved to get the result I want by changing `blendFuncSource ` and  `blendFuncDestination` values, even if I don't understand what these functions are ;)

**Comment by restorer** [comment]
It is Open GL blending functions - http://www.andersriggelsen.dk/glblendfunc.php

However in Sprites renderer it more complicated, because it maps `blendFuncSource` and `blendFuncDestination` to `BlendMode`

| `blendFuncSource` | `blendFuncDestination` | `BlendMode` |
|---|---|---|
| `GL_DST_COLOR` | any | `MULTIPLY` |
| any | `GL_ONE` | `ADD` |
| any other | any other | `NORMAL` |

And inside OpenFL `BlendMode` are mapped back to

| `BlendMode` | Blend equation |  Blend source | Blend destination |
|---|---|---|---|
| `ADD` | `GL_FUNC_ADD`  | `GL_ONE` | `GL_ONE` |
| `MULTIPLY` | `GL_FUNC_ADD` | `GL_DST_COLOR` | `GL_ONE_MINUS_SRC_ALPHA` |
| `NORMAL` | `GL_FUNC_ADD` | `GL_ONE` | `GL_ONE_MINUS_SRC_ALPHA` |

P. S.

I tried every combination of source and destination functions for the fire emitter on white screen (in Particle Designer 2), but only `GL_DST_COLOR` with `GL_ONE_MINUS_SRC_ALPHA` looks good. It is mapped to `MULTIPLY` blend mode (which should map back to the same values), but in OpenFL it looks uglier than in Particle Designer 😢 

P. S. 2.

Probably you can try render particles to texture (in OpenFL this can be achieved by via `BitmapData.draw(...)`).

P. S. 3.

Unfortunately `BitmapData.draw(...)` supports `ColorMatrixFilter` only in flash, and not in other targets 😢
