### ISSUE TITLE
Particles doesnt render at  movieclip's top and left side And Issue with TilemapParticleRenderer

### ISSUE THREAD

**Issue by vega-7** [restorer/zame-haxe-particles#8]
Hi, 

Im using zame haxe particles (1,0,2) for openfl 4.0  and the particles doesnt renderer at any  movieclip top's and/or left's,  looks like the particles doesnt render at negative positions, is that right? if this is the case, how i can fix this ? theres is any property, flag, or method to use? .

by the way in my game (Hula Puzzle V2 Alpha)  zame particles , didnt work correctly, after searching , debugging and testing i found that in this file: zame-haxe-particles/org/zamedev/particles/renderers/TilemapParticleRenderer.hx , line 48: theres an issue with 
this two methods **currentStage.stageWidth** and **currentStage.stageHeight** ,. i replaced those with Lib.current.stage.stageWidth and Lib.current.stage.stageHeight, ( Lib is imported from openfl package --> import openfl.Lib), and now zame particles works flaweless ..

**Comment by restorer** [comment]
> for openfl 4.0 and the particles doesnt renderer at any movieclip top's and/or left's, looks like the particles doesnt render at negative positions, is that right

It should render at negative positions. Do you use `TilemapParticleRenderer`?

> ... TilemapParticleRenderer.hx , line 48: theres an issue with
this two methods ...

This change fixes issue with negative positions?

**Comment by vega-7** [comment]
1.) Yes, im using TilemapParticleRenderer, i dont know why in my case the particles doesnt renderer at negative position, i create a repository where i insolate the issue and you can see  what im talking about.  https://github.com/vega-7/zame-test ,  check the image particles03.jpg this is how haxe is rendering the particles in my machine.

2.) using Lib.current.stage.StageWidth and Lib.current.stage.stageHeight, fixeds other error, where the particles doesnt even show / work.

thanks a lot for your support, effort and time.

**Comment by restorer** [comment]
Strange... Provided sample (https://github.com/vega-7/zame-test) work for me (I test it using following targets: `flash`, `neko`, `mac`, `html5 -Ddom`, `html5 -Dcanvas`, `html5 -Dwebgl`).

I also tried to use directly `TilemapParticleRenderer` instead of `DefaultParticleRenderer.createInstance()` (because in latest version `SpritesParticleRenderer` used for `cpp`).

If you use version from haxelib, try to use latest version from github.

P. S. openfl - 4.9.2, lime - 4.0.3, zame-particles - latest from github

----

Second issue: I look into `TilemapParticleRenderer` at line 48 (where `currentStage` is used). I think it should work correctly, because it is defined as:

```
var currentStage = (stage != null ? stage : openfl.Lib.current.stage);
```

Looks good for me. Do you have ideas why it can work incorrectly?

**Comment by vega-7** [comment]
I was using the version that automatic is installing  using the command...  haxelib install zame-particles.
I unistalled zame-particles and tried a new fresh installation, with no luck. 

But... 

Replacing the files at the zame particles folder  (zame-particles\1,0,2)  With the files of the github version 
. works perfectly, not need of  any fix. 

thanks a lot for your help.

**Comment by restorer** [comment]
Glad to hear. I will publish new version on haxelib soon.
